sudo: false
language: node_js
node_js: "5.1"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
notifications:
  #email: false
    #recipients:
    #  - daggerok@gmail.com
  on_success: change # [always|never|change]
  on_failure: never
